site_name: Finance Knowledge Hub

nav:
  - Home: index.md
  - Stocks: 
    - Overview: stocks/overview.md
    - Metrics: stocks/metrics.md
  - Books:
    - Security Analysis: books/security_analysis.md
    - "Rule #1": books/rule_1.md
    - One Up On Wall Street: books/one_up_on_wall_street.md
    - University of Birkshire: books/university_of_birkshire.md
  # cycles
  # Interest


theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
